package DataAccess.Entity;
// Generated 24/02/2016 05:57:34 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Consulta generated by hbm2java
 */
@Entity
@Table(name="consulta"
    ,catalog="examenes"
)
public class Consulta  implements java.io.Serializable {


     private Integer idConsulta;
     private Paciente paciente;
     private Usuario usuario;
     private boolean aptitud;
     private Date fecha;
     private String diagnostico;
     private String criterio;

    public Consulta() {
    }

	
    public Consulta(Paciente paciente, Usuario usuario, boolean aptitud) {
        this.paciente = paciente;
        this.usuario = usuario;
        this.aptitud = aptitud;
    }
    public Consulta(Paciente paciente, Usuario usuario, boolean aptitud, Date fecha, String diagnostico, String criterio) {
       this.paciente = paciente;
       this.usuario = usuario;
       this.aptitud = aptitud;
       this.fecha = fecha;
       this.diagnostico = diagnostico;
       this.criterio = criterio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idConsulta", unique=true, nullable=false)
    public Integer getIdConsulta() {
        return this.idConsulta;
    }
    
    public void setIdConsulta(Integer idConsulta) {
        this.idConsulta = idConsulta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Paciente_idPaciente", nullable=false)
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Usuario_idUsuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="aptitud", nullable=false)
    public boolean isAptitud() {
        return this.aptitud;
    }
    
    public void setAptitud(boolean aptitud) {
        this.aptitud = aptitud;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fecha", length=19)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="diagnostico", length=200)
    public String getDiagnostico() {
        return this.diagnostico;
    }
    
    public void setDiagnostico(String diagnostico) {
        this.diagnostico = diagnostico;
    }

    
    @Column(name="criterio", length=200)
    public String getCriterio() {
        return this.criterio;
    }
    
    public void setCriterio(String criterio) {
        this.criterio = criterio;
    }




}


