package DataAccess.Entity;
// Generated 24/02/2016 05:57:34 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Paciente generated by hbm2java
 */
@Entity
@Table(name="paciente"
    ,catalog="examenes"
)
public class Paciente  implements java.io.Serializable {


     private Integer idPaciente;
     private Usuario usuario;
     private String nombre;
     private String apellido;
     private String documento;
     private Set consultas = new HashSet(0);

    public Paciente() {
    }

	
    public Paciente(Usuario usuario, String nombre, String apellido, String documento) {
        this.usuario = usuario;
        this.nombre = nombre;
        this.apellido = apellido;
        this.documento = documento;
    }
    public Paciente(Usuario usuario, String nombre, String apellido, String documento, Set consultas) {
       this.usuario = usuario;
       this.nombre = nombre;
       this.apellido = apellido;
       this.documento = documento;
       this.consultas = consultas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPaciente", unique=true, nullable=false)
    public Integer getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Usuario_idUsuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="nombre", nullable=false, length=200)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", nullable=false, length=200)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="documento", nullable=false, length=20)
    public String getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(String documento) {
        this.documento = documento;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="paciente")
    public Set getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Set consultas) {
        this.consultas = consultas;
    }




}


